info:
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /searchFriends:
    post:
      parameters:
      - description: userId
        in: formData
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: '{"code","data", "msg"}'
          schema:
            type: string
      summary: 搜索好友
      tags:
      - 用户模块
  /user/createUser:
    post:
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 确认密码
        in: formData
        name: repassword
        required: true
        type: string
      - description: 手机号码
        in: formData
        name: phone
        type: string
      - description: 邮箱
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"code","data", "msg"}'
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/deleteUser/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: '{"code","data", "msg"}'
          schema:
            type: string
      summary: 删除用户
      tags:
      - 用户模块
  /user/getUserList:
    get:
      responses:
        "200":
          description: '{"code","data", "msg"}'
          schema:
            type: string
      summary: 获取用户列表
      tags:
      - 用户模块
  /user/getUserOnly:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 手机号码
        in: query
        name: phone
        type: string
      - description: 邮箱
        in: query
        name: email
        type: string
      responses:
        "200":
          description: '{"code","data", "msg"}'
          schema:
            type: string
      summary: 获取单一用户
      tags:
      - 用户模块
  /user/updateUser/{id}:
    put:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: 用户名
        in: formData
        name: name
        type: string
      - description: 密码
        in: formData
        name: password
        type: string
      - description: 手机号码
        in: formData
        name: phone
        type: string
      - description: 邮箱
        in: formData
        name: email
        type: string
      responses:
        "200":
          description: '{"code","data", "msg"}'
          schema:
            type: string
      summary: 更新用户
      tags:
      - 用户模块
  /user/userLogin:
    post:
      parameters:
      - description: 用户名
        in: formData
        name: name
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      responses:
        "200":
          description: '{"code","data", "msg"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - 用户模块
swagger: "2.0"
